version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache
          paths:
            - /home/stackage/.stack
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: v2-cache
      - run: stack install --test --system-ghc
      - store_artifacts:
          path: .local/bin/test-exe
          destination: raw-test-output
      - store_test_results:
          path: .stack-work/logs/*
